# The input directory containing all sequence files
input_dir: "example_data/sequences"
# The referance genome location
ref_dir: "example_data/example_ref.fasta"
# Output directory
output_dir: "results/"
# The threshold for N masking 
consen_threshold: 0.8



# Use conda rather tha mamaba
use_conda: True
